# Generated by Django 4.2.2 on 2023-06-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_costcategory_post_postcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='rating',
            new_name='authorRating',
        ),
    ]
